"use client";

import { useState, useEffect } from "react";

export interface NavItem {
  id: string;
  label: string;
}

interface OnThisPageNavProps {
  items: NavItem[];
  title?: string;
  className?: string;
}

/**
 * A sticky "On this page" navigation sidebar with scroll spy functionality.
 * Highlights the currently visible section as the user scrolls.
 * 
 * @example
 * ```tsx
 * const navItems = [
 *   { id: "section-1", label: "Section 1" },
 *   { id: "section-2", label: "Section 2" },
 * ];
 * 
 * <OnThisPageNav items={navItems} />
 * ```
 */
export function OnThisPageNav({ 
  items, 
  title = "On this page",
  className = "" 
}: OnThisPageNavProps) {
  const [activeSection, setActiveSection] = useState<string | null>(() => items[0]?.id ?? null);

  useEffect(() => {
    // If items are provided, use them. Otherwise, scan the DOM for section IDs.
    const targets: string[] = items.length > 0 
      ? items.map(item => item.id) 
      : Array.from(document.querySelectorAll('main div[id], section[id]'))
          .map(el => el.id)
          .filter(id => id && !id.includes('radix') && !id.includes(':'));

    if (targets.length === 0) return;

    const observers: IntersectionObserver[] = [];

    targets.forEach((id) => {
      const element = document.getElementById(id);
      if (element) {
        const observer = new IntersectionObserver(
          (entries) => {
            entries.forEach((entry) => {
              if (entry.isIntersecting) {
                setActiveSection(id);
              }
            });
          },
          {
            rootMargin: "-20% 0px -70% 0px",
            threshold: 0,
          }
        );
        observer.observe(element);
        observers.push(observer);
      }
    });

    return () => {
      observers.forEach((observer) => observer.disconnect());
    };
  }, [items]);

  return (
    <aside className={`hidden xl:block w-48 shrink-0 sticky top-20 h-fit max-h-[calc(100vh-6rem)] overflow-y-auto ${className}`}>
      <nav className="space-y-1">
        <h3 className="text-sm font-semibold text-foreground mb-3">{title}</h3>
        {items.length > 0 ? (
          items.map((item) => {
            const isActive = activeSection === item.id;
            return (
              <a
                key={item.id}
                href={`#${item.id}`}
                className={`block text-sm transition-colors py-1.5 border-l-2 pl-3 -ml-px ${
                  isActive
                    ? "text-client border-client font-medium"
                    : "text-muted-foreground border-transparent hover:text-foreground hover:border-border"
                }`}
              >
                {item.label}
              </a>
            );
          })
        ) : (
          /* Auto-generated links would technically require us to store labels in state too, 
             but for now let's just properly handle the "sticky" requirement the user asked for.
             To fully auto-add, we'd need to parse the DOM labels. 
             Let's implement a quick client-side effect to populates items if missing.
          */
           <AutoGeneratedNav activeSection={activeSection} />
        )}
      </nav>
    </aside>
  );
}

function AutoGeneratedNav({ activeSection }: { activeSection: string | null }) {  const [navItems, setNavItems] = useState<NavItem[]>([]);

  useEffect(() => {
    // Find all potential section targets in the main content area
    // We look for divs with IDs that look like sections
    const elements = document.querySelectorAll('main div[id], section[id]');
    const newItems: NavItem[] = [];

    elements.forEach((el) => {
      // Filter out empty IDs and Radix/internal IDs
      if (el.id && !el.id.includes('radix') && !el.id.includes(':')) {
        // Use the ID to generate a readable label (e.g. "complete-setup-card" -> "Complete Setup Card")
        const label = el.id
          .replace(/-/g, ' ')
          .replace(/\b\w/g, c => c.toUpperCase());
        
        newItems.push({ id: el.id, label });
      }
    });
    
    // Filter out irrelevant IDs if needed, for now grab logical ones
    if (newItems.length > 0) {
      // Wrap in setTimeout to avoid synchronous state update warning in effect
      setTimeout(() => {
        setNavItems(newItems);
      }, 0);
    }
  }, []);

  if (navItems.length === 0) return null;

  return (
    <>
      {navItems.map((item) => {
            const isActive = activeSection === item.id;
            return (
              <a
                key={item.id}
                href={`#${item.id}`}
                className={`block text-sm transition-colors py-1.5 border-l-2 pl-3 -ml-px ${
                  isActive
                    ? "text-client border-client font-medium"
                    : "text-muted-foreground border-transparent hover:text-foreground hover:border-border"
                }`}
              >
                {item.label}
              </a>
            );
          })}
    </>
  );
}
